on:
  push:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  sync-upstream:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: ./.github/scripts/install-hub.sh
      - run: ./.github/scripts/sync-with-master.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
